export const EMP_LOGGED_IN = "EMP_LOGGED_IN";
export const EMP_LOGGED_OUT = "EMP_LOGGED_OUT";
export const EMP_LOGGED_ERR = "EMP_LOGGED_ERR";
export const EMP_LOGGED_IN_SEND_EMAIL = "EMP_LOGGED_IN_SEND_EMAIL";
export const EMP_LOGGED_SEND_EMAIL_ERR="EMP_LOGGED_SEND_EMAIL_ERR";
export const EMP_EMAIL_CONFIRMED="EMP_EMAIL_CONFIRMED";
export const EMP_EMAIL_CONFIRMATION_ERR= "EMP_EMAIL_CONFIRMATION_ERR";
